foundEng = float(input("Foundation English : คะแนนที่ได้ "))
generalBus = float(input("General Business : คะแนนที่ได้ "))
introCom = float(input("Introduction to Computer Systems : คะแนนที่ได้ "))
comPro = float(input("Computer Programming : คะแนนที่ได้ "))
print("--- Your Score ---")
print("Foundation English :",foundEng)
print("General Business :",generalBus)
print("Introduction to Computer Systems :",introCom)
print("Computer Programming :",comPro)